// generated by scripts/generate-tokens.js from tokens/tokens.json — do not edit by hand
import UIKit

enum EmpathyTokens {
    static let colorBrandPrimary = UIColor(red: 0.3098, green: 0.2157, blue: 0.7216, alpha: 1.0)
    static let colorBrandPrimaryDark = UIColor(red: 0.2196, green: 0.1529, blue: 0.5608, alpha: 1.0)
    static let colorBrandRing = UIColor(red: 0.4863, green: 0.3608, blue: 1.0, alpha: 1.0)
    static let colorTextPrimary = UIColor(red: 0.1137, green: 0.1098, blue: 0.1137, alpha: 1.0)
    static let colorTextSecondary = UIColor(red: 0.3569, green: 0.3333, blue: 0.3961, alpha: 1.0)
    static let colorSurfaceTint = UIColor(red: 0.9686, green: 0.9608, blue: 1.0, alpha: 1.0)
    static let colorBorder = UIColor(red: 0.851, green: 0.8314, blue: 0.9373, alpha: 1.0)
    static let colorBorderInput = UIColor(red: 0.6667, green: 0.6353, blue: 0.7098, alpha: 1.0)
    static let colorErrorBorder = UIColor(red: 0.8784, green: 0.6431, blue: 0.6431, alpha: 1.0)
    static let colorErrorText = UIColor(red: 0.7059, green: 0.1373, blue: 0.0941, alpha: 1.0)
    static let colorErrorSurface = UIColor(red: 1.0, green: 0.9608, blue: 0.9608, alpha: 1.0)
    static let colorErrorSurfaceStrong = UIColor(red: 1.0, green: 0.9098, blue: 0.9098, alpha: 1.0)
    static let colorWhite = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
    static let colorDisabled = UIColor(red: 0.5412, green: 0.5412, blue: 0.5412, alpha: 1.0)
    static let colorHostSendSlack = UIColor(red: 0.0, green: 0.4784, blue: 0.3529, alpha: 1.0)
    static let colorHostSendSlackDark = UIColor(red: 0.0, green: 0.3373, blue: 0.2471, alpha: 1.0)
    static let colorHostSendGchat = UIColor(red: 0.0431, green: 0.3412, blue: 0.8157, alpha: 1.0)
    static let colorHostSendGchatDark = UIColor(red: 0.0314, green: 0.2588, blue: 0.6275, alpha: 1.0)
}
